# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessScheduler.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def getPriorityList(self):
        Prioritylist = []
        totalRows = self.JobTable.rowCount()

        col = 0
        for row in range(totalRows):
            item = self.JobTable.item(row, col)
            valueHere = item.text()
            Prioritylist.append(int(valueHere))

        return Prioritylist

    def getATList(self):

        ATlist = []
        totalRows = self.JobTable.rowCount()
        col = 1
        for row in range(totalRows):
            item = self.JobTable.item(row, col)
            valueHere = item.text()
            ATlist.append(int(valueHere))

        return ATlist

    def getBTList(self):
        BTlist = []
        totalRows = self.JobTable.rowCount()

        col = 2
        for row in range(totalRows):
            item = self.JobTable.item(row, col)
            valueHere = item.text()
            BTlist.append(int(valueHere))

        return BTlist

    def getIOBTList(self):
        IOBTlist = []
        totalRows = self.JobTable.rowCount()

        col = 3
        for row in range(totalRows):
            item = self.JobTable.item(row, col)
            valueHere = item.text()
            IOBTlist.append(int(valueHere))

        return IOBTlist

    def getBT2List(self):
        BTlist = []
        totalRows = self.JobTable.rowCount()

        col = 4
        for row in range(totalRows):
            item = self.JobTable.item(row, col)
            valueHere = item.text()
            BTlist.append(int(valueHere))

        return BTlist
    
    def setCTlist(self, CTlist):
        totalRows = self.JobTable.rowCount()

        col = 5
        for row in range(totalRows):
            self.JobTable.setItem(
                row, col, QtWidgets.QTableWidgetItem(str(CTlist[row])))

    def setTATlist(self, TATlist):
        totalRows = self.JobTable.rowCount()

        col = 6
        for row in range(totalRows):
            self.JobTable.setItem(
                row, col, QtWidgets.QTableWidgetItem(str(TATlist[row])))

    def setWTlist(self, WTlist):
        totalRows = self.JobTable.rowCount()

        col = 7
        for row in range(totalRows):
            self.JobTable.setItem(
                row, col, QtWidgets.QTableWidgetItem(str(WTlist[row])))

    def setRTlist(self, RTlist):
        totalRows = self.JobTable.rowCount()

        col = 8
        for row in range(totalRows):
            self.JobTable.setItem(
                row, col, QtWidgets.QTableWidgetItem(str(RTlist[row])))

    def setDefaultPerc(self):
        totalRows = self.JobTable.rowCount()

        col = 9
        for row in range(totalRows):
            self.JobTable.setItem(row, col, QtWidgets.QTableWidgetItem("100"))

    def setDefaultState(self):
        totalRows = self.JobTable.rowCount()

        col = 10
        for row in range(totalRows):
            self.JobTable.setItem(
                row, col, QtWidgets.QTableWidgetItem("Terminated"))
    
    # Solve button Handler

    def solveBtnHandler(self):
        totalJobs = self.JobTable.rowCount()
        ATlist = self.getATList()
        BTlist = self.getBTList()

        # algorithm

        # array for job serial number for reference after sorting according to AT
        jobNumber = []
        for srno in range(totalJobs):
            jobNumber.append(srno)

        # sorting
        for i in range(totalJobs):
            for j in range(i, totalJobs):
                if(ATlist[j] < ATlist[i]):
                    ATlist[j], ATlist[i] = ATlist[i], ATlist[j]
                    BTlist[j], BTlist[i] = BTlist[i], BTlist[j]
                    jobNumber[j], jobNumber[i] = jobNumber[i], jobNumber[j]

        # declaring all the column list
        CTlist = []
        TATlist = []
        WTlist = []
        RTlist = []
        Perlist = []
        Statelist = []

        totalBT = 0

        for i in range(totalJobs):
            CTlist.append(0)
            TATlist.append(0)
            WTlist.append(0)
            RTlist.append(0)
            totalBT += BTlist[i]

        currTime = 0
        totalTAT = 0
        totalWT = 0
        totalRT = 0

        for i in range(totalJobs):
            if(ATlist[i] > currTime):
                currTime = ATlist[i]
            currTime += BTlist[i]
            
            CTlist[i] = currTime
            TATlist[i] = CTlist[i] - ATlist[i]
            WTlist[i] = TATlist[i] - BTlist[i]
            RTlist[i] = currTime - BTlist[i] - ATlist[i]
            totalTAT += TATlist[i]
            totalWT += WTlist[i]
            totalRT += RTlist[i]

        # sorting back
        for i in range(totalJobs):
            for j in range(i, totalJobs):
                if(jobNumber[j] < jobNumber[i]):
                    ATlist[j], ATlist[i] = ATlist[i], ATlist[j]
                    BTlist[j], BTlist[i] = BTlist[i], BTlist[j]
                    CTlist[j], CTlist[i] = CTlist[i], CTlist[j]
                    TATlist[j], TATlist[i] = TATlist[i], TATlist[j]
                    WTlist[j], WTlist[i] = WTlist[i], WTlist[j]
                    RTlist[j], RTlist[i] = RTlist[i], RTlist[j]
                    jobNumber[j], jobNumber[i] = jobNumber[i], jobNumber[j]

        self.setCTlist(CTlist)
        self.setTATlist(TATlist)
        self.setWTlist(WTlist)
        self.setRTlist(RTlist)
        self.setDefaultPerc()
        self.setDefaultState()

        self.AvgTAT.setText(str(round(totalTAT/totalJobs, 5)))
        self.AvgWT.setText(str(round(totalWT/totalJobs, 5)))
        self.AvgRT.setText(str(round(totalRT/totalJobs, 5)))

    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1280, 687)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 687))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 84, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("background: rgb(49, 54, 59);")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MemoryView = QtWidgets.QFrame(self.centralwidget)
        self.MemoryView.setGeometry(QtCore.QRect(10, 10, 261, 271))
        self.MemoryView.setAutoFillBackground(False)
        self.MemoryView.setStyleSheet("*{background: #232629}")
        self.MemoryView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MemoryView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MemoryView.setObjectName("MemoryView")
        self.AlgoLabel = QtWidgets.QLabel(self.MemoryView)
        self.AlgoLabel.setGeometry(QtCore.QRect(20, 14, 111, 16))
        self.AlgoLabel.setStyleSheet("*{\n"
                                     "font-size: 14px;\n"
                                     "color: #ffffff;\n"
                                     "}")
        self.AlgoLabel.setObjectName("AlgoLabel")
        self.AlgoSelector = QtWidgets.QComboBox(self.MemoryView)
        self.AlgoSelector.setGeometry(QtCore.QRect(130, 14, 75, 22))
        self.AlgoSelector.setStyleSheet("*{\n"
                                        "    font-size: 13px;\n"
                                        "    background: #ffffff;\n"
                                        "}")
        self.AlgoSelector.setObjectName("AlgoSelector")
        self.AlgoSelector.addItem("")
        self.AlgoSelector.addItem("")
        self.AlgoSelector.addItem("")
        self.AlgoSelector.addItem("")
        self.AlgoSelector.addItem("")
        self.AlgoSelector.addItem("")
        self.AlgoSelector.addItem("")
        self.ModeLabel = QtWidgets.QLabel(self.MemoryView)
        self.ModeLabel.setGeometry(QtCore.QRect(20, 54, 81, 16))
        self.ModeLabel.setStyleSheet("*{\n"
                                     "font-size: 14px;\n"
                                     "color: #ffffff;\n"
                                     "}")
        self.ModeLabel.setObjectName("ModeLabel")
        self.TypeLabel = QtWidgets.QLabel(self.MemoryView)
        self.TypeLabel.setGeometry(QtCore.QRect(20, 114, 91, 16))
        self.TypeLabel.setStyleSheet("*{\n"
                                     "    font-size: 14px;\n"
                                     "color: #ffffff;\n"
                                     "}")
        self.TypeLabel.setObjectName("TypeLabel")
        self.ContextSwitchLabel = QtWidgets.QLabel(self.MemoryView)
        self.ContextSwitchLabel.setGeometry(QtCore.QRect(20, 174, 111, 16))
        self.ContextSwitchLabel.setStyleSheet("*{\n"
                                              "font-size: 14px;\n"
                                              "color: #ffffff;\n"
                                              "}")
        self.ContextSwitchLabel.setObjectName("ContextSwitchLabel")
        self.ContextSwitchSelector = QtWidgets.QSpinBox(self.MemoryView)
        self.ContextSwitchSelector.setGeometry(QtCore.QRect(130, 174, 42, 22))
        self.ContextSwitchSelector.setStyleSheet("*{\n"
                                                 "background: #ffffff;\n"
                                                 "font-size: 13px;\n"
                                                 "}")
        self.ContextSwitchSelector.setObjectName("ContextSwitchSelector")
        self.TimeQuantumLabel = QtWidgets.QLabel(self.MemoryView)
        self.TimeQuantumLabel.setGeometry(QtCore.QRect(20, 214, 101, 16))
        self.TimeQuantumLabel.setStyleSheet("*{\n"
                                            "font-size: 14px;\n"
                                            "color: #ffffff;\n"
                                            "}")
        self.TimeQuantumLabel.setObjectName("TimeQuantumLabel")
        self.TimeQuantumSelector = QtWidgets.QSpinBox(self.MemoryView)
        self.TimeQuantumSelector.setGeometry(QtCore.QRect(130, 214, 42, 22))
        self.TimeQuantumSelector.setStyleSheet("*{\n"
                                               "background: #ffffff;\n"
                                               "font-size: 13px;\n"
                                               "}")
        self.TimeQuantumSelector.setObjectName("TimeQuantumSelector")
        self.layoutWidget = QtWidgets.QWidget(self.MemoryView)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 52, 115, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.ModeSelector = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.ModeSelector.setContentsMargins(0, 0, 0, 0)
        self.ModeSelector.setObjectName("ModeSelector")
        self.ModeNonPreemptive = QtWidgets.QRadioButton(self.layoutWidget)
        self.ModeNonPreemptive.setStyleSheet("*{\n"
                                             "font-size: 13px;\n"
                                             "color: #ffffff;\n"
                                             "}")
        self.ModeNonPreemptive.setObjectName("ModeNonPreemptive")
        self.ModeSelector.addWidget(self.ModeNonPreemptive)
        self.ModePreemptive = QtWidgets.QRadioButton(self.layoutWidget)
        self.ModePreemptive.setStyleSheet("*{\n"
                                          "font-size: 13px;\n"
                                          "color: #ffffff;\n"
                                          "}")
        self.ModePreemptive.setObjectName("ModePreemptive")
        self.ModeSelector.addWidget(self.ModePreemptive)
        self.layoutWidget1 = QtWidgets.QWidget(self.MemoryView)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 114, 101, 50))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.TypeSelector = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.TypeSelector.setContentsMargins(0, 0, 0, 0)
        self.TypeSelector.setObjectName("TypeSelector")
        self.TypeWithoutIOBT = QtWidgets.QRadioButton(self.layoutWidget1)
        self.TypeWithoutIOBT.setStyleSheet("*{\n"
                                           "font-size: 13px;\n"
                                           "color: #ffffff;\n"
                                           "}")
        self.TypeWithoutIOBT.setObjectName("TypeWithoutIOBT")
        self.TypeSelector.addWidget(self.TypeWithoutIOBT)
        self.TypeWithIOBT = QtWidgets.QRadioButton(self.layoutWidget1)
        self.TypeWithIOBT.setStyleSheet("*{\n"
                                        "font-size: 13px;\n"
                                        "color: #ffffff;\n"
                                        "}")
        self.TypeWithIOBT.setObjectName("TypeWithIOBT")
        self.TypeSelector.addWidget(self.TypeWithIOBT)
        self.JobInputs = QtWidgets.QFrame(self.centralwidget)
        self.JobInputs.setGeometry(QtCore.QRect(280, 10, 991, 271))
        self.JobInputs.setAutoFillBackground(False)
        self.JobInputs.setStyleSheet("*{background: #232629;}")
        self.JobInputs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.JobInputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.JobInputs.setObjectName("JobInputs")
        self.JobTable = QtWidgets.QTableWidget(self.JobInputs)
        self.JobTable.setGeometry(QtCore.QRect(30, 42, 799, 209))
        self.JobTable.setMinimumSize(QtCore.QSize(0, 0))
        self.JobTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.PlaceholderText, brush)
        self.JobTable.setPalette(palette)
        self.JobTable.setAutoFillBackground(False)
        self.JobTable.setStyleSheet("*{\n"
                                    "background: #31363b;\n"
                                    "font-size: 13px;\n"
                                    "color: #ffffff;\n"
                                    "border: 0px solid #000000;\n"
                                    "}\n"
                                    "\n"
                                    "QTableWidget{\n"
                                    "gridline-color: #ffffff;\n"
                                    "}\n"
                                    "\n"
                                    "QHeaderView::section\n"
                                    "{\n"
                                    "background: #31363b;\n"
                                    "font-size: 14px;\n"
                                    "color: #ffffff;\n"
                                    "border: 1px solid #ffffff;\n"
                                    "}\n"
                                    "")
        self.JobTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.JobTable.setLineWidth(2)
        self.JobTable.setMidLineWidth(2)
        self.JobTable.setShowGrid(True)
        self.JobTable.setCornerButtonEnabled(False)
        self.JobTable.setObjectName("JobTable")
        self.JobTable.setColumnCount(11)
        self.JobTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.JobTable.setHorizontalHeaderItem(10, item)
        self.JobTable.horizontalHeader().setVisible(True)
        self.JobTable.horizontalHeader().setCascadingSectionResizes(False)
        self.JobTable.horizontalHeader().setDefaultSectionSize(65)
        self.JobTable.horizontalHeader().setHighlightSections(False)
        self.JobTable.horizontalHeader().setMinimumSectionSize(30)
        self.JobTable.verticalHeader().setVisible(True)
        self.JobTable.verticalHeader().setCascadingSectionResizes(False)
        self.JobTable.verticalHeader().setHighlightSections(False)
        self.AvgTATLabel = QtWidgets.QLabel(self.JobInputs)
        self.AvgTATLabel.setGeometry(QtCore.QRect(852, 62, 91, 16))
        self.AvgTATLabel.setStyleSheet("font-size: 13px;\n"
                                       "color: #ffffff;")
        self.AvgTATLabel.setObjectName("AvgTATLabel")
        self.AvgWTLabel = QtWidgets.QLabel(self.JobInputs)
        self.AvgWTLabel.setGeometry(QtCore.QRect(852, 116, 81, 16))
        self.AvgWTLabel.setStyleSheet("font-size: 13px;\n"
                                      "color: #ffffff;")
        self.AvgWTLabel.setObjectName("AvgWTLabel")
        self.AvgRTLabel = QtWidgets.QLabel(self.JobInputs)
        self.AvgRTLabel.setGeometry(QtCore.QRect(852, 170, 81, 16))
        self.AvgRTLabel.setStyleSheet("font-size: 13px;\n"
                                      "color: #ffffff;")
        self.AvgRTLabel.setObjectName("AvgRTLabel")
        self.AvgTAT = QtWidgets.QLineEdit(self.JobInputs)
        self.AvgTAT.setGeometry(QtCore.QRect(852, 88, 117, 20))
        self.AvgTAT.setStyleSheet("background: #31363b;\n"
                                  "font-size: 12px;\n"
                                  "color: #ffffff;")
        self.AvgTAT.setText("")
        self.AvgTAT.setReadOnly(True)
        self.AvgTAT.setObjectName("AvgTAT")
        self.AvgWT = QtWidgets.QLineEdit(self.JobInputs)
        self.AvgWT.setGeometry(QtCore.QRect(852, 142, 117, 20))
        self.AvgWT.setStyleSheet("background: #31363b;\n"
                                 "font-size: 12px;\n"
                                 "color: #ffffff;")
        self.AvgWT.setReadOnly(True)
        self.AvgWT.setObjectName("AvgWT")
        self.AvgRT = QtWidgets.QLineEdit(self.JobInputs)
        self.AvgRT.setGeometry(QtCore.QRect(852, 196, 117, 20))
        self.AvgRT.setStyleSheet("background: #31363b;\n"
                                 "font-size: 12px;\n"
                                 "color: #ffffff;")
        self.AvgRT.setReadOnly(True)
        self.AvgRT.setObjectName("AvgRT")
        self.JobNoLabel = QtWidgets.QLabel(self.JobInputs)
        self.JobNoLabel.setGeometry(QtCore.QRect(34, 16, 105, 16))
        self.JobNoLabel.setStyleSheet("*{\n"
                                      "font-size: 14px;\n"
                                      "color: #ffffff;\n"
                                      "}")
        self.JobNoLabel.setObjectName("JobNoLabel")
        self.JobNo = QtWidgets.QSpinBox(self.JobInputs)
        self.JobNo.setGeometry(QtCore.QRect(148, 12, 42, 22))
        self.JobNo.setStyleSheet("*{\n"
                                 "background: #ffffff;\n"
                                 "color: #000000;\n"
                                 "font-size: 13px;\n"
                                 "}")
        self.JobNo.setObjectName("JobNo")
        self.GoBtn = QtWidgets.QPushButton(self.JobInputs)
        self.GoBtn.setGeometry(QtCore.QRect(206, 12, 43, 23))
        self.GoBtn.setStyleSheet("*{\n"
                                 "background: #ffffff;\n"
                                 "font-size: 13px;\n"
                                 "}")
        self.GoBtn.setObjectName("GoBtn")
        self.SolveBtn = QtWidgets.QPushButton(self.JobInputs)
        self.SolveBtn.setGeometry(QtCore.QRect(744, 12, 69, 23))
        self.SolveBtn.setStyleSheet("*{\n"
                                    "background: #ffffff;\n"
                                    "font-size: 13px;\n"
                                    "}")
        self.SolveBtn.setObjectName("SolveBtn")
        self.ResetBtn = QtWidgets.QPushButton(self.JobInputs)
        self.ResetBtn.setGeometry(QtCore.QRect(662, 12, 69, 23))
        self.ResetBtn.setStyleSheet("*{\n"
                                    "background: #ffffff;\n"
                                    "font-size: 13px;\n"
                                    "}")
        self.ResetBtn.setObjectName("ResetBtn")
        self.ImportBtn = QtWidgets.QPushButton(self.JobInputs)
        self.ImportBtn.setGeometry(QtCore.QRect(274, 12, 69, 23))
        self.ImportBtn.setStyleSheet("*{\n"
                                     "background: #ffffff;\n"
                                     "font-size: 13px;\n"
                                     "}")
        self.ImportBtn.setObjectName("ImportBtn")
        self.QueueView = QtWidgets.QFrame(self.centralwidget)
        self.QueueView.setGeometry(QtCore.QRect(10, 290, 1261, 221))
        self.QueueView.setAutoFillBackground(False)
        self.QueueView.setStyleSheet("*{background: #232629}")
        self.QueueView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QueueView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QueueView.setObjectName("QueueView")
        self.JobQueue = QtWidgets.QLineEdit(self.QueueView)
        self.JobQueue.setGeometry(QtCore.QRect(40, 60, 281, 41))
        self.JobQueue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.JobQueue.setStyleSheet("*{\n"
                                    "background: #31363b;\n"
                                    "color: #ffffff;\n"
                                    "font-size: 15px;\n"
                                    "}")
        self.JobQueue.setText("")
        self.JobQueue.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.JobQueue.setDragEnabled(False)
        self.JobQueue.setReadOnly(True)
        self.JobQueue.setObjectName("JobQueue")
        self.ReadyQueue = QtWidgets.QLineEdit(self.QueueView)
        self.ReadyQueue.setGeometry(QtCore.QRect(380, 60, 281, 41))
        self.ReadyQueue.setStyleSheet("*{\n"
                                      "background: #31363b;\n"
                                      "color: #ffffff;\n"
                                      "font-size: 15px;\n"
                                      "}")
        self.ReadyQueue.setText("")
        self.ReadyQueue.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ReadyQueue.setDragEnabled(False)
        self.ReadyQueue.setReadOnly(True)
        self.ReadyQueue.setObjectName("ReadyQueue")
        self.TerminatedQueue = QtWidgets.QLineEdit(self.QueueView)
        self.TerminatedQueue.setGeometry(QtCore.QRect(860, 60, 281, 41))
        self.TerminatedQueue.setStyleSheet("*{\n"
                                           "background: #31363b;\n"
                                           "color: #ffffff;\n"
                                           "font-size: 15px;\n"
                                           "}")
        self.TerminatedQueue.setText("")
        self.TerminatedQueue.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.TerminatedQueue.setReadOnly(True)
        self.TerminatedQueue.setObjectName("TerminatedQueue")
        self.CPUinQueue = QtWidgets.QLineEdit(self.QueueView)
        self.CPUinQueue.setGeometry(QtCore.QRect(730, 50, 81, 61))
        self.CPUinQueue.setStyleSheet("*{\n"
                                      "background: #31363b;\n"
                                      "color: #ffffff;\n"
                                      "font-size: 20px;\n"
                                      "}")
        self.CPUinQueue.setAlignment(QtCore.Qt.AlignCenter)
        self.CPUinQueue.setReadOnly(True)
        self.CPUinQueue.setObjectName("CPUinQueue")
        self.IODeviceinQueue = QtWidgets.QLineEdit(self.QueueView)
        self.IODeviceinQueue.setGeometry(QtCore.QRect(320, 140, 81, 61))
        self.IODeviceinQueue.setStyleSheet("*{\n"
                                           "background: #31363b;\n"
                                           "color: #ffffff;\n"
                                           "font-size: 20px;\n"
                                           "}")
        self.IODeviceinQueue.setAlignment(QtCore.Qt.AlignCenter)
        self.IODeviceinQueue.setReadOnly(True)
        self.IODeviceinQueue.setObjectName("IODeviceinQueue")
        self.IOQueue = QtWidgets.QLineEdit(self.QueueView)
        self.IOQueue.setGeometry(QtCore.QRect(470, 150, 281, 41))
        self.IOQueue.setStyleSheet("*{\n"
                                   "background: #31363b;\n"
                                   "color: #ffffff;\n"
                                   "font-size: 15px;\n"
                                   "}")
        self.IOQueue.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.IOQueue.setReadOnly(True)
        self.IOQueue.setObjectName("IOQueue")
        self.JobQueueLabel = QtWidgets.QLabel(self.QueueView)
        self.JobQueueLabel.setGeometry(QtCore.QRect(50, 40, 71, 16))
        self.JobQueueLabel.setStyleSheet("font-size: 13px;\n"
                                         "color: #ffffff;")
        self.JobQueueLabel.setObjectName("JobQueueLabel")
        self.ReadyQueueLabel = QtWidgets.QLabel(self.QueueView)
        self.ReadyQueueLabel.setGeometry(QtCore.QRect(390, 40, 81, 16))
        self.ReadyQueueLabel.setStyleSheet("font-size: 13px;\n"
                                           "color: #ffffff;")
        self.ReadyQueueLabel.setObjectName("ReadyQueueLabel")
        self.CPULabel = QtWidgets.QLabel(self.QueueView)
        self.CPULabel.setGeometry(QtCore.QRect(740, 30, 31, 16))
        self.CPULabel.setStyleSheet("font-size: 13px;\n"
                                    "color: #ffffff;")
        self.CPULabel.setObjectName("CPULabel")
        self.TerminatedQueueLabel = QtWidgets.QLabel(self.QueueView)
        self.TerminatedQueueLabel.setGeometry(QtCore.QRect(870, 40, 121, 16))
        self.TerminatedQueueLabel.setStyleSheet("font-size: 13px;\n"
                                                "color: #ffffff;")
        self.TerminatedQueueLabel.setObjectName("TerminatedQueueLabel")
        self.IOQueueLabel = QtWidgets.QLabel(self.QueueView)
        self.IOQueueLabel.setGeometry(QtCore.QRect(480, 130, 81, 16))
        self.IOQueueLabel.setStyleSheet("font-size: 13px;\n"
                                        "color: #ffffff;")
        self.IOQueueLabel.setObjectName("IOQueueLabel")
        self.IODeviceLabel = QtWidgets.QLabel(self.QueueView)
        self.IODeviceLabel.setGeometry(QtCore.QRect(358, 120, 71, 16))
        self.IODeviceLabel.setStyleSheet("font-size: 13px;\n"
                                         "color: #ffffff;")
        self.IODeviceLabel.setObjectName("IODeviceLabel")
        self.TimeLabel = QtWidgets.QLabel(self.QueueView)
        self.TimeLabel.setGeometry(QtCore.QRect(1180, 70, 61, 16))
        self.TimeLabel.setStyleSheet("font-size: 20px;\n"
                                     "color: #ffffff;")
        self.TimeLabel.setObjectName("TimeLabel")
        self.JobtoReadyArrow = QtWidgets.QLabel(self.QueueView)
        self.JobtoReadyArrow.setGeometry(QtCore.QRect(322, 72, 59, 16))
        self.JobtoReadyArrow.setText("")
        self.JobtoReadyArrow.setPixmap(QtGui.QPixmap("Arrows/JobtoReady.png"))
        self.JobtoReadyArrow.setObjectName("JobtoReadyArrow")
        self.ReadytoCPUArrow = QtWidgets.QLabel(self.QueueView)
        self.ReadytoCPUArrow.setGeometry(QtCore.QRect(662, 72, 69, 16))
        self.ReadytoCPUArrow.setText("")
        self.ReadytoCPUArrow.setPixmap(QtGui.QPixmap("Arrows/ReadytoCPU.png"))
        self.ReadytoCPUArrow.setObjectName("ReadytoCPUArrow")
        self.CPUtoTerminatedArrow = QtWidgets.QLabel(self.QueueView)
        self.CPUtoTerminatedArrow.setGeometry(QtCore.QRect(812, 72, 49, 16))
        self.CPUtoTerminatedArrow.setText("")
        self.CPUtoTerminatedArrow.setPixmap(
            QtGui.QPixmap("Arrows/CPUtoTerminated.png"))
        self.CPUtoTerminatedArrow.setObjectName("CPUtoTerminatedArrow")
        self.IOQueuetoIODeviceArrow = QtWidgets.QLabel(self.QueueView)
        self.IOQueuetoIODeviceArrow.setGeometry(QtCore.QRect(404, 162, 67, 16))
        self.IOQueuetoIODeviceArrow.setText("")
        self.IOQueuetoIODeviceArrow.setPixmap(
            QtGui.QPixmap("Arrows/IOQueuetoIODevice.png"))
        self.IOQueuetoIODeviceArrow.setObjectName("IOQueuetoIODeviceArrow")
        self.CPUtoIOQueueArrow = QtWidgets.QLabel(self.QueueView)
        self.CPUtoIOQueueArrow.setGeometry(QtCore.QRect(752, 112, 47, 63))
        self.CPUtoIOQueueArrow.setText("")
        self.CPUtoIOQueueArrow.setPixmap(
            QtGui.QPixmap("Arrows/CPUtoIOQueue.png"))
        self.CPUtoIOQueueArrow.setObjectName("CPUtoIOQueueArrow")
        self.CPUtoReadyArrow = QtWidgets.QLabel(self.QueueView)
        self.CPUtoReadyArrow.setGeometry(QtCore.QRect(344, 18, 441, 57))
        self.CPUtoReadyArrow.setText("")
        self.CPUtoReadyArrow.setPixmap(QtGui.QPixmap("Arrows/CPUtoReady.png"))
        self.CPUtoReadyArrow.setObjectName("CPUtoReadyArrow")
        self.IODevicetoReadyArrow = QtWidgets.QLabel(self.QueueView)
        self.IODevicetoReadyArrow.setGeometry(QtCore.QRect(344, 86, 17, 59))
        self.IODevicetoReadyArrow.setText("")
        self.IODevicetoReadyArrow.setPixmap(
            QtGui.QPixmap("Arrows/IODevicetoReady.png"))
        self.IODevicetoReadyArrow.setObjectName("IODevicetoReadyArrow")
        self.TimerLabel = QtWidgets.QLabel(self.QueueView)
        self.TimerLabel.setGeometry(QtCore.QRect(1176, 88, 57, 55))
        self.TimerLabel.setStyleSheet("font-size: 30px;\n"
                                      "color: #ffffff;")
        self.TimerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerLabel.setObjectName("TimerLabel")
        self.CPUtoTerminatedArrow.raise_()
        self.CPUtoIOQueueArrow.raise_()
        self.ReadytoCPUArrow.raise_()
        self.IOQueuetoIODeviceArrow.raise_()
        self.IODevicetoReadyArrow.raise_()
        self.JobtoReadyArrow.raise_()
        self.CPUtoReadyArrow.raise_()
        self.JobQueue.raise_()
        self.ReadyQueue.raise_()
        self.TerminatedQueue.raise_()
        self.CPUinQueue.raise_()
        self.IODeviceinQueue.raise_()
        self.IOQueue.raise_()
        self.JobQueueLabel.raise_()
        self.ReadyQueueLabel.raise_()
        self.CPULabel.raise_()
        self.TerminatedQueueLabel.raise_()
        self.IOQueueLabel.raise_()
        self.IODeviceLabel.raise_()
        self.TimeLabel.raise_()
        self.TimerLabel.raise_()
        self.GanttChart = QtWidgets.QFrame(self.centralwidget)
        self.GanttChart.setGeometry(QtCore.QRect(10, 520, 1261, 101))
        self.GanttChart.setAutoFillBackground(False)
        self.GanttChart.setStyleSheet("*{background: #232629}")
        self.GanttChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GanttChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GanttChart.setObjectName("GanttChart")
        self.GanttChartLabel = QtWidgets.QLabel(self.GanttChart)
        self.GanttChartLabel.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.GanttChartLabel.setStyleSheet("font-size: 13px;\n"
                                           "color: #ffffff;")
        self.GanttChartLabel.setObjectName("GanttChartLabel")
        self.GanttChartTable = QtWidgets.QTableWidget(self.GanttChart)
        self.GanttChartTable.setGeometry(QtCore.QRect(20, 30, 1229, 65))
        self.GanttChartTable.setStyleSheet("*{\n"
                                           "background: #31363b;\n"
                                           "font-size: 12px;\n"
                                           "color: #ffffff;\n"
                                           "border: 1px solid #ffffff;\n"
                                           "}\n"
                                           "\n"
                                           "QTableWidget{\n"
                                           "gridline-color: #ffffff;\n"
                                           "}\n"
                                           "\n"
                                           "QHeaderView::section\n"
                                           "{\n"
                                           "background: #31363b;\n"
                                           "font-size: 12px;\n"
                                           "color: #ffffff;\n"
                                           "border: 1px solid #ffffff;\n"
                                           "}\n"
                                           "")
        self.GanttChartTable.setShowGrid(True)
        self.GanttChartTable.setObjectName("GanttChartTable")
        self.GanttChartTable.setColumnCount(0)
        self.GanttChartTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.GanttChartTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.GanttChartTable.setVerticalHeaderItem(1, item)
        self.GanttChartTable.horizontalHeader().setVisible(False)
        self.GanttChartTable.horizontalHeader().setDefaultSectionSize(39)
        self.GanttChartTable.verticalHeader().setVisible(True)
        self.GanttChartTable.verticalHeader().setDefaultSectionSize(23)
        self.GanttChartTable.verticalHeader().setMinimumSectionSize(5)
        self.Controls = QtWidgets.QFrame(self.centralwidget)
        self.Controls.setGeometry(QtCore.QRect(10, 630, 1261, 35))
        self.Controls.setAutoFillBackground(False)
        self.Controls.setStyleSheet("*{background: #232629}")
        self.Controls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Controls.setObjectName("Controls")
        self.PlayBtn = QtWidgets.QPushButton(self.Controls)
        self.PlayBtn.setGeometry(QtCore.QRect(52, 6, 75, 23))
        self.PlayBtn.setStyleSheet("*{\n"
                                   "background: #ffffff;\n"
                                   "font-size: 13px;\n"
                                   "}")
        self.PlayBtn.setObjectName("PlayBtn")
        self.PauseBtn = QtWidgets.QPushButton(self.Controls)
        self.PauseBtn.setGeometry(QtCore.QRect(136, 6, 75, 23))
        self.PauseBtn.setStyleSheet("*{\n"
                                    "background: #ffffff;\n"
                                    "font-size: 13px;\n"
                                    "}")
        self.PauseBtn.setObjectName("PauseBtn")
        self.PrevBtn = QtWidgets.QPushButton(self.Controls)
        self.PrevBtn.setGeometry(QtCore.QRect(700, 6, 93, 23))
        self.PrevBtn.setStyleSheet("*{\n"
                                   "background: #ffffff;\n"
                                   "font-size: 13px;\n"
                                   "}")
        self.PrevBtn.setObjectName("PrevBtn")
        self.NextBtn = QtWidgets.QPushButton(self.Controls)
        self.NextBtn.setGeometry(QtCore.QRect(800, 6, 75, 23))
        self.NextBtn.setStyleSheet("*{\n"
                                   "background: #ffffff;\n"
                                   "font-size: 13px;\n"
                                   "}")
        self.NextBtn.setObjectName("NextBtn")
        self.ScheduleProgressBar = QtWidgets.QProgressBar(self.Controls)
        self.ScheduleProgressBar.setGeometry(QtCore.QRect(288, 6, 349, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.PlaceholderText, brush)
        self.ScheduleProgressBar.setPalette(palette)
        self.ScheduleProgressBar.setStyleSheet("*{\n"
                                               "background: #ffffff;\n"
                                               "font-size: 13px;\n"
                                               "color: #ffffff;\n"
                                               "}")
        self.ScheduleProgressBar.setProperty("value", 24)
        self.ScheduleProgressBar.setObjectName("ScheduleProgressBar")
        self.GraphBtn = QtWidgets.QPushButton(self.Controls)
        self.GraphBtn.setGeometry(QtCore.QRect(964, 6, 117, 23))
        self.GraphBtn.setStyleSheet("*{\n"
                                    "background: #ffffff;\n"
                                    "font-size: 13px;\n"
                                    "}")
        self.GraphBtn.setObjectName("GraphBtn")
        self.DownloadBtn = QtWidgets.QPushButton(self.Controls)
        self.DownloadBtn.setGeometry(QtCore.QRect(1098, 6, 81, 23))
        self.DownloadBtn.setStyleSheet("*{\n"
                                       "background: #ffffff;\n"
                                       "font-size: 13px;\n"
                                       "}")
        self.DownloadBtn.setObjectName("DownloadBtn")
        self.HelpBtn = QtWidgets.QPushButton(self.Controls)
        self.HelpBtn.setGeometry(QtCore.QRect(1196, 6, 53, 23))
        self.HelpBtn.setStyleSheet("*{\n"
                                   "background: #ffffff;\n"
                                   "font-size: 13px;\n"
                                   "}")
        self.HelpBtn.setObjectName("HelpBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Process Scheduler"))
        self.AlgoLabel.setText(_translate("MainWindow", "Select Algorithm:"))
        self.AlgoSelector.setItemText(0, _translate("MainWindow", "FCFS"))
        self.AlgoSelector.setItemText(1, _translate("MainWindow", "SJF"))
        self.AlgoSelector.setItemText(2, _translate("MainWindow", "SRTF"))
        self.AlgoSelector.setItemText(3, _translate("MainWindow", "RR"))
        self.AlgoSelector.setItemText(4, _translate("MainWindow", "LJF"))
        self.AlgoSelector.setItemText(5, _translate("MainWindow", "LRTF"))
        self.AlgoSelector.setItemText(6, _translate("MainWindow", "Priority"))
        self.ModeLabel.setText(_translate("MainWindow", "Select Mode:"))
        self.TypeLabel.setText(_translate("MainWindow", "Select Type:"))
        self.ContextSwitchLabel.setText(
            _translate("MainWindow", "Context Switch:"))
        self.TimeQuantumLabel.setText(
            _translate("MainWindow", "Time Quantum:"))
        self.ModeNonPreemptive.setText(
            _translate("MainWindow", "Non Preemptive"))
        self.ModePreemptive.setText(_translate("MainWindow", "Preemptive"))
        self.TypeWithoutIOBT.setText(_translate("MainWindow", "Without IOBT"))
        self.TypeWithIOBT.setText(_translate("MainWindow", "With IOBT"))
        self.JobTable.setSortingEnabled(False)
        item = self.JobTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Priority"))
        item = self.JobTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "AT"))
        item = self.JobTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "BT"))
        item = self.JobTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IOBT"))
        item = self.JobTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "BT"))
        item = self.JobTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CT"))
        item = self.JobTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TAT"))
        item = self.JobTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "WT"))
        item = self.JobTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "RT"))
        item = self.JobTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "%"))
        item = self.JobTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "State"))
        self.AvgTATLabel.setText(_translate("MainWindow", "Average TAT:"))
        self.AvgWTLabel.setText(_translate("MainWindow", "Average WT:"))
        self.AvgRTLabel.setText(_translate("MainWindow", "Average RT:"))
        self.JobNoLabel.setText(_translate("MainWindow", "Number of Jobs:"))
        self.GoBtn.setText(_translate("MainWindow", "Go"))
        self.SolveBtn.setText(_translate("MainWindow", "Solve"))
        self.ResetBtn.setText(_translate("MainWindow", "Reset"))
        self.ImportBtn.setText(_translate("MainWindow", "Import"))
        self.JobQueueLabel.setText(_translate("MainWindow", "Job Queue"))
        self.ReadyQueueLabel.setText(_translate("MainWindow", "Ready Queue"))
        self.CPULabel.setText(_translate("MainWindow", "CPU"))
        self.TerminatedQueueLabel.setText(
            _translate("MainWindow", "Terminated Queue"))
        self.IOQueueLabel.setText(_translate("MainWindow", "I/O Queue"))
        self.IODeviceLabel.setText(_translate("MainWindow", "I/O Device"))
        self.TimeLabel.setText(_translate("MainWindow", "TIME"))
        self.TimerLabel.setText(_translate("MainWindow", "00"))
        self.GanttChartLabel.setText(_translate("MainWindow", "Gantt Chart"))
        item = self.GanttChartTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Job"))
        item = self.GanttChartTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        self.PlayBtn.setText(_translate("MainWindow", "Play"))
        self.PauseBtn.setText(_translate("MainWindow", "Pause"))
        self.PrevBtn.setText(_translate("MainWindow", "Previous Step"))
        self.NextBtn.setText(_translate("MainWindow", "Next Step"))
        self.GraphBtn.setText(_translate("MainWindow", "Generate Graph"))
        self.DownloadBtn.setText(_translate("MainWindow", "Download"))
        self.HelpBtn.setText(_translate("MainWindow", "Help"))

        # Adding Handler on Click to solve button.
        self.SolveBtn.clicked.connect(self.solveBtnHandler)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
